# Generated by Django 3.0.5 on 2020-04-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps_create', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='etl_job_file',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='etl_job_list',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='source_type_file',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='source_type_table1',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='source_type_table2',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='target_type_file',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='target_type_table1',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='target_type_table2',
        ),
    ]
