# Generated by Django 3.0.5 on 2020-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
