# Generated by Django 3.0.5 on 2020-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
